### ISSUE TITLE
climate_ip integration fail to start

### ISSUE THREAD

**Issue by yufretti** [atxbyea/samsungrac#47] opened 2022-07-07 06:39 UTC
Hello, for a few days I have been experiencing a problem: climate_ip does not start anymore.
In the logs, I see this error message:

2022-07-07 05:50:55 ERROR (SyncWorker_11) [custom_components.climate_ip.climate] Request execution failed. Stack trace:
2022-07-07 05:50:57 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform climate_ip
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 220, in state
return HVACMode(self.hvac_mode).value
File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
return cls.__new__(cls, value)
File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
raise ve_exc
ValueError: 'unknown' is not a valid HVACMode

The message repeats several times, once for each air conditioner that I have configured in the configuration.yaml.

The version of HA I'm using is this:
Home Assistant 2022.7.0
Supervisor 2022.06.2
Operating System 8.2 Frontend 20220706.0 - latest

The version of climate_ip I am using is 4.0

This is my setup:
climate:
- platform: climate_ip
  name: 'AC Cucina'
  config_file: 'samsungrac.yaml'
  ip_address: 'myip'
  token: 'mytoken'
  cert: 'ac14k_m.pem'
  
- platform: climate_ip
  name: 'AC Sala'
  config_file: 'samsungrac.yaml'
  ip_address: '192.168.168.104'
  token: '9XI6E6jV9w'
  cert: 'ac14k_m.pem'
  
- platform: climate_ip
  name: 'AC Camera Yuri and Roby'
  config_file: 'samsungrac.yaml'
  ip_address: 'myip'
  token: 'mytoken'
  cert: 'ac14k_m.pem'
  
- platform: climate_ip
  name: 'AC Camera Leo'
  config_file: 'samsungrac.yaml'
  ip_address: 'myip'
  token: 'mytoken'
  cert: 'ac14k_m.pem'
  
- platform: climate_ip
  name: 'AC Camera Cri'
  config_file: 'samsungrac.yaml'
  ip_address: 'myip'
  token: 'mytoken'
  cert: 'ac14k_m.pem'

I installed climate_ip a few weeks ago, and it worked fine for a while. Now it doesn't work anymore.

I have already tried to turn the air conditioners off and on again, but the problem did not go away.

How can I solve?
Thank you!

Juri

**Comment by hoeselr** [comment] 2022-07-07 07:42
same issue on our side

**Comment by giig982** [comment] 2022-07-07 10:18
it's a duplicate of #46 and #44

**Closed** 2022-07-07 11:33 UTC
