### ISSUE TITLE
Performance - it brings down HA

### ISSUE THREAD

**Issue by Jens-Wymeersch** [atxbyea/samsungrac#5] opened 2020-10-04 07:37 UTC
Dear,

After testing Sebu's custom component and seeing HA performance issues. I was looking at the MQTT built from Sasha (https://github.com/gsasha/hvac_ip_mqtt_bridge) but there were bugs in the code.
Today I looked at your fork but still it seems not to be scalable enough for 6 A/Cs and more. Some of my components just don't work anymore. Also if I look my HDD moves to 90% utilisation. Anything you can do about it ?

I get the following error logs:

'Logger: custom_components.climate_ip.climate
Source: custom_components/climate_ip/samsung_2878.py:236
Integration: climate_ip (documentation, issues)
First occurred: 10:02:22 (224 occurrences)
Last logged: 10:29:58

Traceback (most recent call last): File "/config/custom_components/climate_ip/samsung_2878.py", line 219, in send_socket_command sslSocket = self.socket File "/config/custom_components/climate_ip/samsung_2878.py", line 281, in socket self.create_connection() File "/config/custom_components/climate_ip/samsung_2878.py", line 270, in create_connection sslSocket.connect((cfg.host, cfg.port)) File "/usr/local/lib/python3.8/ssl.py", line 1342, in connect self._real_connect(addr, False) File "/usr/local/lib/python3.8/ssl.py", line 1329, in _real_connect super().connect(addr) ConnectionRefusedError: [Errno 111] Connection refused

Logger: homeassistant.components.climate
Source: /usr/local/lib/python3.8/asyncio/events.py:81
Integration: Klimaat (documentation, issues)
First occurred: 10:02:34 (6 occurrences)
Last logged: 10:02:34

Setup of climate platform climate_ip is taking over 10 seconds.`

regards,
Jens

**Comment by atxbyea** [comment] 2020-10-05 09:47
@Jens-Wymeersch 
[Errno 111] Connection refused implies that whatever you are trying to reach isn't willing to talk to you.
Are you sure you are connecting to a supported device \ the correct IP ?

HDD utilization at 90% sounds very strange, what is your storage device ? On what platform ?

**Comment by Jens-Wymeersch** [comment] 2020-10-05 12:41
> @Jens-Wymeersch
> [Errno 111] Connection refused implies that whatever you are trying to reach isn't willing to talk to you.
> Are you sure you are connecting to a supported device \ the correct IP ?
> 
> HDD utilization at 90% sounds very strange, what is your storage device ? On what platform ?

Hi @atxbyea, thank you for reaching out. I'm running HA on a virtualbox machine on top of i7 16G RAM windows machine. 
I can see all A/Cs and control them (very slowly though). 

So there is no connection problem besides the A/C in the Kitchen which I need to reboot (which is one error).

Your code brings HA to crawling speed and at some point stops working. This behavior starts to be visible from the moment I integrate 3 A/Cs and onwards.

**Comment by wifi75** [comment] 2020-10-05 16:10
@atxbyea it's true, this component works but it greatly affects the home assistant's performance, in practice it slows it down

**Comment by atxbyea** [comment] 2020-10-05 16:52
Interesting,I've run the component for over a year, I have probably over 1000 entities in HA and I notice no slowdown of HA

**Comment by Jens-Wymeersch** [comment] 2020-10-05 18:25
If you only have a few A/Cs, you don't see any real degradation in performance. With 6, it brings HA on its knees.

**Comment by thadius83** [comment] 2020-10-05 21:39
> If you only have a few A/Cs, you don't see any real degradation in performance. With 6, it brings HA on its knees. Hence the idea to move towards a MQTT bridge architecture.

Just a quick question. What unit are you using for controlling the 3-6 AC's, and what model are they?

**Comment by Jens-Wymeersch** [comment] 2020-10-06 01:35
Hi, 
Although I bought 4 of my 6 A/Cs just a couple of months ago, they are all port 2878 A/Cs. Model AR18HSFSSWKN, AR09HSFSSWKN x 3, AR12HSFSSWKN X 2 

Regards,
Jens

**Comment by wifi75** [comment] 2020-10-06 09:00
@atxbyea I have two AC, but fir example when script running shelly for example it is slow in executing the command to switch on a lamp or shutter, when stopped the script becomes very fast

**Comment by Jens-Wymeersch** [comment] 2020-10-06 09:08
I've found the problem with my HDD and will do another run later today.

**Comment by d3m3trius** [comment] 2020-10-06 20:09
It used to happen also to me, sometimes the AC become unresponsive (for reason not depending from HA or this components), and when this happen, the calls to retrieve the status fails, the log is flooded with errors and HA become unresponsive.

It would be useful to introduce a mechanism that, we a number of calls fails, set the entity as unavailable and stop making continuous call to the AC. Maybe it could retry after an hours or so to check if the AC responds or it is still unavailable.

**Comment by atxbyea** [comment] 2020-10-08 09:01
@d3m3trius @Jens-Wymeersch have you tried the new 3.2 release if the issue persists ?

**Comment by ishioni** [comment] 2020-10-08 09:48
> It used to happen also to me, sometimes the AC become unresponsive (for reason not depending from HA or this component), and when this happen, the calls to retrieve the status fails, the log is flooded with errors and HA become unresponsive.
> 
> It would be useful to introduce a mechanism that, we a number of calls fail, set the entity as unavailable and stop making continuous call to the AC. Maybe it could retry after an hours or so to check if the AC responds or it is still unavailable.

Not sure which model you have, but I see this behaviour from time to time where the unit will keep disconnecting and connecting to wifi in a period of around 3 minutes, for a random time. I kept troubleshooting this for a long time, and after carefully eliminating any other factor (I even soldered an external antenna), I came to the conclusion that the firmware inside can't ping something inside the samsung cloud, goes into reboot and tries again. At some point I'll hijack the serial lines inside the module and find out exactly what's going on, but for now there's not much one can do about it

The bit about the device being unavailable is right on the money tho, it's not implemented as of now

**Comment by Jens-Wymeersch** [comment] 2020-10-08 09:51
@atxbyea I've been quite busy the last few days. I'll do the tests this weekend.

**Comment by Jens-Wymeersch** [comment] 2020-10-08 21:08
Gents,

I've installed the component on my test system and it worked quite well. thank you @atxbyea @ishioni 

still I get the following errors 
`2020-10-08 23:57:41 WARNING (MainThread) [homeassistant.setup] Setup of unifi is taking over 10 seconds.
2020-10-08 23:57:41 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.
2020-10-08 23:57:41 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.
2020-10-08 23:57:41 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2020-10-08 23:57:41 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
2020-10-08 23:57:41 WARNING (MainThread) [homeassistant.setup] Setup of tag is taking over 10 seconds.
2020-10-08 23:57:41 WARNING (MainThread) [homeassistant.setup] Setup of input_number is taking over 10 seconds.
2020-10-08 23:57:41 WARNING (MainThread) [homeassistant.setup] Setup of input_datetime is taking over 10 seconds.
2020-10-08 23:57:41 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform climate_ip is taking over 10 seconds.
2020-10-08 23:57:41 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform climate_ip is taking over 10 seconds.
2020-10-08 23:57:41 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform climate_ip is taking over 10 seconds.
2020-10-08 23:57:41 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform climate_ip is taking over 10 seconds.
2020-10-08 23:57:41 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform climate_ip is taking over 10 seconds.
2020-10-08 23:57:41 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform climate_ip is taking over 10 seconds.`

**Comment by Jens-Wymeersch** [comment] 2020-10-09 07:41
@atxbyea @ishioni Yesterday evening I moved to production with the component and till now it running smoothly. Thank you so much !

**Comment by d3m3trius** [comment] 2020-10-09 22:59
Disconnected power to the AC to "simulate" its disconnection, and tested old and new version in the same condition.

I didn't notice differences between 3.1.and 3.2. The performance seems similar too, but to be honest this time I didn't notice drops in performance in the old version either. It's possible that performance starts to drop after several hours of failed connections, and that's why I didn't notice any difference.

In both versions the logs are flooded with error messages every 3 and 12 seconds:
`2020-10-10 00:33:21 ERROR (MainThread) [custom_components.climate_ip.climate] Sending command failed
2020-10-10 00:33:21 ERROR (MainThread) [custom_components.climate_ip.climate] Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/climate_ip/samsung_2878.py", line 219, in send_socket_command
    sslSocket = self.socket
  File "/home/homeassistant/.homeassistant/custom_components/climate_ip/samsung_2878.py", line 281, in socket
    self.create_connection()
  File "/home/homeassistant/.homeassistant/custom_components/climate_ip/samsung_2878.py", line 270, in create_connection
    sslSocket.connect((cfg.host, cfg.port))
  File "/usr/lib/python3.8/ssl.py", line 1342, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.8/ssl.py", line 1329, in _real_connect
    super().connect(addr)
OSError: [Errno 113] No route to host`

**Comment by atxbyea** [comment] 2020-10-10 12:44
Please keep monitoring it for performance drop @d3m3trius.

I have no issues with performance with just one, so can't reproduce it either.
The error message you see there would be normal when a device is off wifi \ powered off anyway.

**Comment by d3m3trius** [comment] 2020-10-10 21:13
So far HA performance are still good, so I think async calls solve the issue.
The AC in the meantime has become unresponsive for real.
The log grows rapidly at a rate of 10MB/day for every AC with connection problems.

I think that logging could be greatly reduced removing the traceback (moving to different log level?), and it would be useful to log ip or name of the AC that does not respond.
However, the best thing would be to set the entity as unavailable and stop continuous call to the unresponsive AC.

**Comment by atxbyea** [comment] 2020-10-15 13:47
Yeah, I don't have that issue as my AC is avaliable 24\7, hopefully someone comes along that knows how to fix this at some point

**Comment by Jens-Wymeersch** [comment] 2020-10-15 19:06
My Home assistant broke down the last few days and I had to start over again. At least I got ride of some errors doing so... 
I went to the new release of HA and now your @atxbyea custom components brings my HA down again... I'll do another try again this evening but it's not really encouraging !

**Comment by dapuzz** [comment] 2020-10-26 13:39
> It would be useful to introduce a mechanism that, we a number of calls fail, set the entity as unavailable and stop making continuous call to the AC. Maybe it could retry after an hours or so to check if the AC responds or it is still unavailable.

Same issue for me. I have 2 AC, one of them has unstable connection. Logs get full of message [Errno 113] No route to host and HA became very slow.
I have to comment the entity in my configuration.yaml and force restart.

**Comment by d3m3trius** [comment] 2020-10-27 00:43
Not a solution but, to to avoid destroying the disk with useless writes, I modified locally the code from self.logger.error(...) to self.logger.info(...) on line 232 and 236 of samsung_2878.py.

**Comment by atxbyea** [comment] 2020-11-16 10:18
> Not a solution but, to to avoid destroying the disk with useless writes, I modified locally the code from self.logger.error(...) to self.logger.info(...) on line 232 and 236 of samsung_2878.py.

Could you submit that as a PR and I can review it @d3m3trius ?

**Comment by atxbyea** [comment] 2020-11-23 12:55
Merged @d3m3trius PR, upping release

**Comment by postlund** [comment] 2020-12-22 21:31
One culprit to the issue is this line:

https://github.com/atxbyea/samsungrac/blob/0e4ffd9f7111243d92d531439b2efca07f95fa9f/custom_components/climate_ip/climate.py#L259

It runs blocking synchronous code in async context, I.e. you block the entire event loop so that *nothing* can run for 1.5s every scan interval. Since @Jens-Wymeersch has six units, that sums up to 6*1,5s=9s which is 9/15=60% of the time.

The connection logic is synchronous, so I suggest that you stay away from `async_` methods in entity classes. You can implement the update method like this:

```python
    def update(self):
        time.sleep(self._update_delay)
        _LOGGER.info("async_update")
        self.rac.update_state()

```

**Comment by Jens-Wymeersch** [comment] 2020-12-22 22:34
@atxbyea would it be possible to have a look what Pierre wrote above and evaluate if we can add it to the new release ?

**Comment by Jens-Wymeersch** [comment] 2020-12-23 16:52
Just to report with the fix of Pierre, I was able to run the CC in my primary HA environment for the first time and without significant performance issues.

**Comment by atxbyea** [comment] 2020-12-24 09:41
@Jens-Wymeersch @postlund if you can submit a PR for that I can merge it when I have time

**Comment by postlund** [comment] 2020-12-24 10:22
@atxbyea I can submit one later.

**Comment by postlund** [comment] 2020-12-24 18:08
PR submitted as #20.

**Closed** 2020-12-24 21:38 UTC
Labels: bug
